### ISSUE TITLE
current farm Current Farm [Category of Offshore Production Area] (row 43 main)

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101_Portrayal-Catalogue#114]
- [x] "Current Farm", use RENERG51.svg, See spec at: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/63#issuecomment-1185197537
- [x] Combine "Wave Farm" (row 105 main), use RENERG51.svg,  https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/55#issuecomment-1185197139
- [x] Combine "Solar Farm" (row 83 main),  use RENERG51.svg, https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/67#issuecomment-1185201815
- [ ] Combine "Offshore Wind Farm" (row 66 main)  https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/68
- [x]  Combine "Tank Farm (row 93 main) {see naming comment below} https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/54#issuecomment-1185206684

RENERG51.svg file from here: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/67#issuecomment-1229903774

**Comment by mikan66** [comment]
Tank Farm only, (needs test data) commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/7a9626591a0df09a47a25cb6550c16d4df10e149

**Comment by mikan66** [comment]
Rename Tank Farm from 2022_TNKFRM.svg to TNKFRM.svg

**Comment by mikan66** [comment]
Name change only, see commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/fe08459f3f4758cff568e3a109d9e88f89c759e3

**Comment by mikan66** [comment]
Forced "Wind Farm" to test new rule logic.  Similar results for other categories.  Is this the desired results?

Wind Farm with  Symbolized boundaries:
![image](https://user-images.githubusercontent.com/4913543/188005714-0c697406-d349-45b2-873b-b1c0a3ce6671.png)

Wind Farm with Plain boundaries:
![image](https://user-images.githubusercontent.com/4913543/188005840-8f722a56-71f4-43be-ab76-b86e71451c66.png)

Forced "Seabed Material Extraction Area", i.e. category == 5:
![image](https://user-images.githubusercontent.com/4913543/188006436-eb20945c-68a6-4a6d-bfe1-a1652b74a9ed.png)
![image](https://user-images.githubusercontent.com/4913543/188006491-8fe01764-5224-46a5-9bda-ef1cc00e0196.png)

**Comment by MikusRL** [comment]
I understand that: 1) the simplified boundary color was agreed to be CHGRD, and 2) that the conditional symbology is addition, not replacement, to the existing center symbol. @alvarosanuy Correct? That was my concern and outcome of our discussion at Portray SubWG GitHub, right? 

As a background note - I created the additional symbols, as I also understood, that when conditional symbology kicks in, then it is replacing the symbol, but it can be understood from the standard as well, that manufacturers will have to add additional symbols to the existing one, but displace the additional conditional ones so that they are not overlapping with the main one. Including not overlapping dynamically also the ship symbol, if own ship is displayed centered, but the last is not a concern as of this test concern, as I understand.

**Comment by mikan66** [comment]
I have some mistakes trying to get to fancy in the rule logic, sorry.  The original rule focused on special processing with regard to Tank Farm (4) only.  We now have to consider 2,3,6, and 1 with any remaining values as well.  I will try to craft up some new pictures.

**Comment by mikan66** [comment]
Wind Farm (1) with forced 'restriction' = 1 (anchoring prohibited):
![image](https://user-images.githubusercontent.com/4913543/188118683-b980da47-e722-4d23-9271-c42ee097fda7.png)
![image](https://user-images.githubusercontent.com/4913543/188118779-58dd00c8-62ae-4641-a581-f2bff3672f7c.png)

I think we should go case-by-case in this manner of forcing the potrayal for all these new symbols until we agree I have it correct.

**Comment by MikusRL** [comment]
@mikan66 I think you have not used the latest uploaded wind farm symbol. In examples it is I think the previous one. The last Wind Farm symbol I uploaded is also now 9.94mm one with 0.64 stroke width.

**Comment by mikan66** [comment]
I will correct to 52, any other issues with this Feature and associated portrayal at this time?

**Comment by MikusRL** [comment]
For me I miss a little bit info to understand the invalid value examples. You "loose the center symbol, but get shifted exclamation mark in the circle instead? If the main symbol is unknown how to portray, should it not be a question mark? Or I mix it up with something else. Thanks.

**Comment by mikan66** [comment]
The S-52 ported rule  default is (no attributes examined):    OSPARE	  	SY(CTYARE51);LS(DASH,2,CHMGD);CS(RESTRN01).  We have introduced several new symbols based on attribute values for categoryOfOffshoreProductionArea.  We can change the default, but that may require a new issue for discussion by the group.

CTYARE51 symbol does look shifted downward within the symbol svg itself.
![image](https://user-images.githubusercontent.com/4913543/188278399-eb762826-ff5a-4cd0-b210-1b5ebfc40f8d.png)

**Comment by alvarosanuy** [comment]
I understand that all the 'companion' symbols referred by S-52 CSP RESCSP02 have some in-built offsets in order to seat 'around' (bearing and distance) the main symbol (linked to the value of **categoryOfffshoreProductionArea**). Refer to S-52 PresLib Ed 4.0(.3) - section 8.5.1 (Fig 4)]. This includes CTYARE51.
Accordingly, in S-52, when **categoryOfffshoreProductionArea** is set to 'Unknown' or populated with a value that does not link to a dedicated symbol, these 'companion' symbols are still depicted based on the values of the **restriction** attribute and will look off centred. RSRDEF51 is used when undefined restrictions exist.
The only thing we are doing by creating new symbols linked to specific **categoryOfffshoreProductionArea** values is reducing the instances when this occur. The general behaviour, as I see it, follows current S-52 practices and shouldn't be a problem for PC 1.0.2.
If somebody wants to propose a new 'default' symbol that is easier to relate to 'offshore production areas' and is not off-set from the centre of the surface, that's fine but this should be done by opening a new dedicated Github issue and aiming for PC 1.1.0 or later.
Happy to hear other (probably more knowledgeable) points of view though ......

**Comment by mikan66** [comment]
See commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/6f0a528d91c73f9a5e49bb39993aac2faa948690

**Comment by mikan66** [comment]
@alvarosanuy  Using test datasets 101AA00DS0014.000 and 7 this generally agrees but I'm confused about Production/Storage Area with categoryOfProductionArea = Solar Farm (12),  this has no symbol.  Is that what the final intention? 
![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/982159af-91ec-47a5-bae6-d87aaf2bd97c)

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/4913543/ccfd2cf2-05dc-470b-9b91-2bd21e093f9d)

**Comment by alvarosanuy** [comment]
@mikan66 - Your question above is about the portrayal of **ProductionStorageArea** feature not **OffshoreProductionArea** (this GitHub issue).

The portrayal of **ProductionStorageArea** has been mapped as per S-52 PRDARE. In S-52 CATPRA=12 (win farm) does only show the boundary of the area using LS(DASH,1,LANDF), but no central symbol.

In short, the depiction in the TDS and the on-shore ECDIS is correct. Having said this, I agree that there may be merits to use the 'renewable energy' symbol (RENERG51) created for **OffshoreProductionArea** (Solar, Wave & Current Farms) for **ProductionStorageArea** with **categoryOfProductionArea**=12, but this will need a new proposal in the PsWG GitHub space. In reality we would need new symbols because RENERG51 is grey in colour and not Buff (non conspicuous)or Black (conspicuous) as it could be needed ....
